name: Web CI
on: [push, pull_request]
jobs:
  build-studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
        working-directory: apps/sfb_studio
      - run: npm run build
        working-directory: apps/sfb_studio
